#============================================================================
#  data.s - GENERATED by tools/gen_data.py -- DO NOT EDIT BY HAND
#  sprite art, species stats, type chart, moves, maps, dialogue.
#============================================================================
.intel_syntax noprefix
.include "defs.inc"

.section .rodata

# ----------------------------------------------------------- sprites -----
.globl spr_charmander
spr_charmander:
    .ascii "   ___   ^\n  / o \\ /|\n <  w  > |\n  \\___/ \\|\n  /| |\\  v\n\0"
.globl spr_bulbasaur
spr_bulbasaur:
    .ascii "  _#_     \n / o \\    \n<  w  >   \n \\___/    \n /| |\\    \n\0"
.globl spr_squirtle
spr_squirtle:
    .ascii "   ___    \n  / o \\   \n <  w  >  \n  \\___/   \n   '''    \n\0"
.globl spr_pidgey
spr_pidgey:
    .ascii "   __     \n  /  \\    \n < o o >  \n  \\__/    \n   /\\     \n\0"
.globl spr_rattata
spr_rattata:
    .ascii "  /\\_/\\   \n < o o >  \n  \\_w_/   \n   | |    \n  ^   ^   \n\0"
.globl spr_oddish
spr_oddish:
    .ascii "   @@@    \n  @ o @   \n  @@@@    \n   | |    \n  ^^ ^^   \n\0"
.globl spr_meowth
spr_meowth:
    .ascii "  /\\_/\\   \n ( o o )  \n  \\ w /   \n  /| |\\   \n  ^   ^   \n\0"
.globl spr_pikachu
spr_pikachu:
    .ascii "  /\\_/\\   \n < ^ ^ >  \n  \\ w /   \n  /| |\\   \n  ^   ^   \n\0"
.globl spr_magikarp
spr_magikarp:
    .ascii "  __      \n / o \\    \n<  w  >   \n \\__/     \n /  \\     \n\0"
.globl spr_geodude
spr_geodude:
    .ascii "  ,---,   \n ( o o )  \n  \\___/   \n /|   |\\  \n  ^   ^   \n\0"

# -------------------------------------------------------- type chart -----
.globl type_chart
.globl type_chart
type_chart:
    .byte 4,4,4,4,4,4,4,4,2,4
    .byte 4,2,2,8,4,4,4,8,2,4
    .byte 4,8,2,2,4,4,4,4,8,8
    .byte 4,2,8,2,4,2,2,2,8,8
    .byte 4,4,8,2,2,4,8,4,4,0
    .byte 4,4,4,8,4,2,4,4,2,2
    .byte 4,4,4,8,2,4,4,8,2,4
    .byte 4,2,4,8,4,2,2,4,2,4
    .byte 4,8,4,4,4,4,8,8,4,2
    .byte 4,8,4,2,8,8,0,2,8,4

.globl type_names
type_names:
    .quad str_ty_NORMAL
    .quad str_ty_FIRE
    .quad str_ty_WATER
    .quad str_ty_GRASS
    .quad str_ty_ELECTR
    .quad str_ty_POISON
    .quad str_ty_FLYING
    .quad str_ty_BUG
    .quad str_ty_ROCK
    .quad str_ty_GROUND
.globl type_colours
type_colours:
    .byte C_GRAY,C_RED,C_CYAN,C_GREEN,C_BYELLOW,C_MAGENTA,C_BWHITE,C_GREEN,C_YELLOW,C_YELLOW
.globl str_ty_NORMAL
str_ty_NORMAL: .asciz "Normal"
.globl str_ty_FIRE
str_ty_FIRE: .asciz "Fire"
.globl str_ty_WATER
str_ty_WATER: .asciz "Water"
.globl str_ty_GRASS
str_ty_GRASS: .asciz "Grass"
.globl str_ty_ELECTR
str_ty_ELECTR: .asciz "Electr"
.globl str_ty_POISON
str_ty_POISON: .asciz "Poison"
.globl str_ty_FLYING
str_ty_FLYING: .asciz "Flying"
.globl str_ty_BUG
str_ty_BUG: .asciz "Bug"
.globl str_ty_ROCK
str_ty_ROCK: .asciz "Rock"
.globl str_ty_GROUND
str_ty_GROUND: .asciz "Ground"

# ------------------------------------------------------------- moves -----
.globl move_table
.globl move_table
move_table:
    .quad str_mv_TACKLE                 # +0  name
    .byte 35,T_NORMAL,0,35       # +8  power,type,effect,pp
    .zero 4                            # entries are V_SZ (16) bytes
    .quad str_mv_SCRATCH                 # +0  name
    .byte 40,T_NORMAL,0,35       # +8  power,type,effect,pp
    .zero 4                            # entries are V_SZ (16) bytes
    .quad str_mv_EMBER                 # +0  name
    .byte 40,T_FIRE,0,25       # +8  power,type,effect,pp
    .zero 4                            # entries are V_SZ (16) bytes
    .quad str_mv_VINE_WHIP                 # +0  name
    .byte 45,T_GRASS,0,25       # +8  power,type,effect,pp
    .zero 4                            # entries are V_SZ (16) bytes
    .quad str_mv_WATER_GUN                 # +0  name
    .byte 40,T_WATER,0,25       # +8  power,type,effect,pp
    .zero 4                            # entries are V_SZ (16) bytes
    .quad str_mv_THUNDERSHOCK                 # +0  name
    .byte 40,T_ELECTR,6,30       # +8  power,type,effect,pp
    .zero 4                            # entries are V_SZ (16) bytes
    .quad str_mv_GUST                 # +0  name
    .byte 40,T_FLYING,0,35       # +8  power,type,effect,pp
    .zero 4                            # entries are V_SZ (16) bytes
    .quad str_mv_BITE                 # +0  name
    .byte 55,T_NORMAL,0,25       # +8  power,type,effect,pp
    .zero 4                            # entries are V_SZ (16) bytes
    .quad str_mv_QUICK_ATTACK                 # +0  name
    .byte 35,T_NORMAL,5,30       # +8  power,type,effect,pp
    .zero 4                            # entries are V_SZ (16) bytes
    .quad str_mv_GROWL                 # +0  name
    .byte 0,T_NORMAL,1,40       # +8  power,type,effect,pp
    .zero 4                            # entries are V_SZ (16) bytes
    .quad str_mv_TAIL_WHIP                 # +0  name
    .byte 0,T_NORMAL,2,30       # +8  power,type,effect,pp
    .zero 4                            # entries are V_SZ (16) bytes
    .quad str_mv_RECOVER                 # +0  name
    .byte 0,T_NORMAL,3,20       # +8  power,type,effect,pp
    .zero 4                            # entries are V_SZ (16) bytes
    .quad str_mv_ROCK_THROW                 # +0  name
    .byte 50,T_ROCK,0,15       # +8  power,type,effect,pp
    .zero 4                            # entries are V_SZ (16) bytes
    .quad str_mv_POISON_STING                 # +0  name
    .byte 30,T_POISON,6,35       # +8  power,type,effect,pp
    .zero 4                            # entries are V_SZ (16) bytes
.globl str_mv_TACKLE
str_mv_TACKLE: .asciz "TACKLE"
.globl str_mv_SCRATCH
str_mv_SCRATCH: .asciz "SCRATCH"
.globl str_mv_EMBER
str_mv_EMBER: .asciz "EMBER"
.globl str_mv_VINE_WHIP
str_mv_VINE_WHIP: .asciz "VINE WHIP"
.globl str_mv_WATER_GUN
str_mv_WATER_GUN: .asciz "WATER GUN"
.globl str_mv_THUNDERSHOCK
str_mv_THUNDERSHOCK: .asciz "THUNDERSHOCK"
.globl str_mv_GUST
str_mv_GUST: .asciz "GUST"
.globl str_mv_BITE
str_mv_BITE: .asciz "BITE"
.globl str_mv_QUICK_ATTACK
str_mv_QUICK_ATTACK: .asciz "QUICK ATTACK"
.globl str_mv_GROWL
str_mv_GROWL: .asciz "GROWL"
.globl str_mv_TAIL_WHIP
str_mv_TAIL_WHIP: .asciz "TAIL WHIP"
.globl str_mv_RECOVER
str_mv_RECOVER: .asciz "RECOVER"
.globl str_mv_ROCK_THROW
str_mv_ROCK_THROW: .asciz "ROCK THROW"
.globl str_mv_POISON_STING
str_mv_POISON_STING: .asciz "POISON STING"

# ----------------------------------------------------------- species -----
.globl species_table
.globl species_table
species_table:
    .quad str_sp_CHARMANDER, spr_charmander
    .byte 39,52,43,65,T_FIRE,T_FIRE,45,62        # base stats, types, catch rate, exp yield
    .byte 1,9,2,8,10,5,C_BRED        # moves, sprite w/h, sprite colour
    .byte 10,16,0,0,0,0,0,0,0     # +31 evolves into (0xFF = never), +32 at level
    .quad str_sp_BULBASAUR, spr_bulbasaur
    .byte 45,49,49,45,T_GRASS,T_POISON,45,64        # base stats, types, catch rate, exp yield
    .byte 0,9,3,13,10,5,C_BGREEN        # moves, sprite w/h, sprite colour
    .byte 11,16,0,0,0,0,0,0,0     # +31 evolves into (0xFF = never), +32 at level
    .quad str_sp_SQUIRTLE, spr_squirtle
    .byte 44,48,65,43,T_WATER,T_WATER,45,63        # base stats, types, catch rate, exp yield
    .byte 0,10,4,7,10,5,C_BCYAN        # moves, sprite w/h, sprite colour
    .byte 12,16,0,0,0,0,0,0,0     # +31 evolves into (0xFF = never), +32 at level
    .quad str_sp_PIDGEY, spr_pidgey
    .byte 40,45,40,56,T_NORMAL,T_FLYING,255,50        # base stats, types, catch rate, exp yield
    .byte 6,8,0,9,10,5,C_BWHITE        # moves, sprite w/h, sprite colour
    .byte 13,18,0,0,0,0,0,0,0     # +31 evolves into (0xFF = never), +32 at level
    .quad str_sp_RATTATA, spr_rattata
    .byte 30,56,35,72,T_NORMAL,T_NORMAL,255,51        # base stats, types, catch rate, exp yield
    .byte 0,10,8,7,10,5,C_BMAGENTA        # moves, sprite w/h, sprite colour
    .byte 255,0,0,0,0,0,0,0,0     # +31 evolves into (0xFF = never), +32 at level
    .quad str_sp_ODDISH, spr_oddish
    .byte 45,50,55,30,T_GRASS,T_POISON,255,52        # base stats, types, catch rate, exp yield
    .byte 13,3,9,0,10,5,C_BGREEN        # moves, sprite w/h, sprite colour
    .byte 255,0,0,0,0,0,0,0,0     # +31 evolves into (0xFF = never), +32 at level
    .quad str_sp_MEOWTH, spr_meowth
    .byte 40,45,35,90,T_NORMAL,T_NORMAL,255,58        # base stats, types, catch rate, exp yield
    .byte 1,9,7,8,10,5,C_BYELLOW        # moves, sprite w/h, sprite colour
    .byte 255,0,0,0,0,0,0,0,0     # +31 evolves into (0xFF = never), +32 at level
    .quad str_sp_PIKACHU, spr_pikachu
    .byte 35,55,40,90,T_ELECTR,T_ELECTR,190,82        # base stats, types, catch rate, exp yield
    .byte 5,8,10,0,10,5,C_BYELLOW        # moves, sprite w/h, sprite colour
    .byte 255,0,0,0,0,0,0,0,0     # +31 evolves into (0xFF = never), +32 at level
    .quad str_sp_MAGIKARP, spr_magikarp
    .byte 20,10,55,80,T_WATER,T_WATER,255,40        # base stats, types, catch rate, exp yield
    .byte 0,0,0,0,10,5,C_BRED        # moves, sprite w/h, sprite colour
    .byte 255,0,0,0,0,0,0,0,0     # +31 evolves into (0xFF = never), +32 at level
    .quad str_sp_GEODUDE, spr_geodude
    .byte 40,80,100,20,T_ROCK,T_GROUND,255,60        # base stats, types, catch rate, exp yield
    .byte 12,0,10,7,10,5,C_GRAY        # moves, sprite w/h, sprite colour
    .byte 255,0,0,0,0,0,0,0,0     # +31 evolves into (0xFF = never), +32 at level
    .quad str_sp_CHARMELEON, spr_charmander
    .byte 58,64,58,80,T_FIRE,T_FIRE,45,142        # base stats, types, catch rate, exp yield
    .byte 2,1,9,7,10,5,C_BRED        # moves, sprite w/h, sprite colour
    .byte 255,0,0,0,0,0,0,0,0     # +31 evolves into (0xFF = never), +32 at level
    .quad str_sp_IVYSAUR, spr_bulbasaur
    .byte 60,62,63,60,T_GRASS,T_POISON,45,141        # base stats, types, catch rate, exp yield
    .byte 3,0,13,9,10,5,C_BGREEN        # moves, sprite w/h, sprite colour
    .byte 255,0,0,0,0,0,0,0,0     # +31 evolves into (0xFF = never), +32 at level
    .quad str_sp_WARTORTLE, spr_squirtle
    .byte 59,63,80,58,T_WATER,T_WATER,45,143        # base stats, types, catch rate, exp yield
    .byte 4,0,7,10,10,5,C_BCYAN        # moves, sprite w/h, sprite colour
    .byte 255,0,0,0,0,0,0,0,0     # +31 evolves into (0xFF = never), +32 at level
    .quad str_sp_PIDGEOTTO, spr_pidgey
    .byte 63,60,55,71,T_NORMAL,T_FLYING,120,113        # base stats, types, catch rate, exp yield
    .byte 6,8,0,9,10,5,C_BWHITE        # moves, sprite w/h, sprite colour
    .byte 255,0,0,0,0,0,0,0,0     # +31 evolves into (0xFF = never), +32 at level
.globl str_sp_CHARMANDER
str_sp_CHARMANDER: .asciz "CHARMANDER"
.globl str_sp_BULBASAUR
str_sp_BULBASAUR: .asciz "BULBASAUR"
.globl str_sp_SQUIRTLE
str_sp_SQUIRTLE: .asciz "SQUIRTLE"
.globl str_sp_PIDGEY
str_sp_PIDGEY: .asciz "PIDGEY"
.globl str_sp_RATTATA
str_sp_RATTATA: .asciz "RATTATA"
.globl str_sp_ODDISH
str_sp_ODDISH: .asciz "ODDISH"
.globl str_sp_MEOWTH
str_sp_MEOWTH: .asciz "MEOWTH"
.globl str_sp_PIKACHU
str_sp_PIKACHU: .asciz "PIKACHU"
.globl str_sp_MAGIKARP
str_sp_MAGIKARP: .asciz "MAGIKARP"
.globl str_sp_GEODUDE
str_sp_GEODUDE: .asciz "GEODUDE"
.globl str_sp_CHARMELEON
str_sp_CHARMELEON: .asciz "CHARMELEON"
.globl str_sp_IVYSAUR
str_sp_IVYSAUR: .asciz "IVYSAUR"
.globl str_sp_WARTORTLE
str_sp_WARTORTLE: .asciz "WARTORTLE"
.globl str_sp_PIDGEOTTO
str_sp_PIDGEOTTO: .asciz "PIDGEOTTO"

.globl n_species
.globl n_species
n_species: .byte 14
.globl n_moves
.globl n_moves
n_moves: .byte 14

# ------------------------------------------------------------- items -----
.globl item_names
.globl item_names
item_names:
    .quad str_it_POTION
    .quad str_it_POKe_BALL
.globl str_it_POTION
str_it_POTION: .asciz "POTION"
.globl str_it_POKe_BALL
str_it_POKe_BALL: .asciz "POKe BALL"
.globl n_items
.globl n_items
n_items: .byte 2

# ------------------------------------------------------- tile graphics ---
.globl tile_defs
.globl tile_defs
tile_defs:
    .quad g_c46
    .quad g_c32
    .quad g_c32
    .quad g_c46
    .byte 42,42,42,42,1,0,0,0
    .quad g_c34
    .quad g_c34
    .quad g_c34
    .quad g_c34
    .byte 162,162,162,162,1,1,0,0
    .quad g_c35
    .quad g_c35
    .quad g_c35
    .quad g_c35
    .byte 42,42,42,42,0,0,0,0
    .quad g_c35
    .quad g_c35
    .quad g_c35
    .quad g_c35
    .byte 127,127,127,127,0,0,0,0
    .quad g_c46
    .quad g_c32
    .quad g_c32
    .quad g_c46
    .byte 7,7,7,7,1,0,0,0
    .quad g_c126
    .quad g_c126
    .quad g_c126
    .quad g_c126
    .byte 78,78,78,78,0,0,0,0
    .quad g_c95
    .quad g_c95
    .quad g_c124
    .quad g_c124
    .byte 25,25,25,25,0,0,0,0
    .quad g_c91
    .quad g_c93
    .quad g_c124
    .quad g_c124
    .byte 127,127,127,127,1,0,0,0
    .quad g_c61
    .quad g_c61
    .quad g_c61
    .quad g_c61
    .byte 59,59,59,59,0,0,0,0
    .quad g_c95
    .quad g_c95
    .quad g_c47
    .quad g_c124
    .byte 43,43,43,43,0,0,0,0
    .quad g_c111
    .quad g_c32
    .quad g_c32
    .quad g_c111
    .byte 43,43,43,43,0,0,0,0
    .quad g_c42
    .quad g_c32
    .quad g_c32
    .quad g_c42
    .byte 45,45,45,45,1,0,0,0
    .quad g_c32
    .quad g_c32
    .quad g_c32
    .quad g_c32
    .byte 59,59,59,59,1,0,0,0
    .quad g_c35
    .quad g_c35
    .quad g_c35
    .quad g_c35
    .byte 31,31,31,31,0,0,0,0
    .quad g_c32
    .quad g_c32
    .quad g_c32
    .quad g_c32
    .byte 0,0,0,0,0,0,0,0

.globl n_tiles
.globl n_tiles
n_tiles: .byte 15

.globl char_to_tile
.globl char_to_tile
char_to_tile:
    .byte 14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,2,9,14,14,14,14,14,10,14,1,14,0,14,14,14,14,14,14,14,14,14,14,14,12,14,14,14,14,14
    .byte 14,14,14,8,7,14,11,14,14,14,14,14,4,13,14,14,14,14,6,14,14,14,14,3,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,5,14

# ----------------------------------------------------- entity sprites ---
.globl ent_sprite_defs
.globl ent_sprite_defs
ent_sprite_defs:
    .quad g_c64
    .quad g_c64
    .quad g_c124
    .quad g_c124
    .byte 9,9,15,15,0,0,0,0
    .quad g_c111
    .quad g_c111
    .quad g_c124
    .quad g_c124
    .byte 14,14,15,15,0,0,0,0
    .quad g_c111
    .quad g_c111
    .quad g_c124
    .quad g_c124
    .byte 13,13,15,15,0,0,0,0
    .quad g_c111
    .quad g_c111
    .quad g_c35
    .quad g_c35
    .byte 15,15,13,13,0,0,0,0
    .quad g_c64
    .quad g_c64
    .quad g_c124
    .quad g_c124
    .byte 12,12,15,15,0,0,0,0
    .quad g_c111
    .quad g_c111
    .quad g_c35
    .quad g_c35
    .byte 15,15,7,7,0,0,0,0

.globl n_ent_sprites
.globl n_ent_sprites
n_ent_sprites: .byte 6

# every glyph used by the tile/sprite tables, in one block so the
# fixed-size entry records stay contiguous
.globl g_c46
g_c46: .asciz "."
.globl g_c32
g_c32: .asciz " "
.globl g_c34
g_c34: .asciz "\""
.globl g_c35
g_c35: .asciz "#"
.globl g_c126
g_c126: .asciz "~"
.globl g_c95
g_c95: .asciz "_"
.globl g_c124
g_c124: .asciz "|"
.globl g_c91
g_c91: .asciz "["
.globl g_c93
g_c93: .asciz "]"
.globl g_c61
g_c61: .asciz "="
.globl g_c47
g_c47: .asciz "/"
.globl g_c111
g_c111: .asciz "o"
.globl g_c42
g_c42: .asciz "*"
.globl g_c64
g_c64: .asciz "@"

# ----- map 0: PALLET TOWN (40x24) spawn (19, 10) -----
.globl map0_name
map0_name: .asciz "PALLET TOWN"
.globl map0_tiles
map0_tiles:
    .ascii "##################....##################"
    .ascii "##################....##################"
    .ascii "#..................::$.................#"
    .ascii "#..................::..................#"
    .ascii "#.....RRRRRRRR.....::.....RRRRRRRR.....#"
    .ascii "#.....RRRRRRRR..F..::..F..RRRRRRRR.....#"
    .ascii "#.....RRRRRRRR.....::.....RRRRRRRR.....#"
    .ascii "#.....RRRRDRRR.....::.....RRRRDRRR.....#"
    .ascii "#..................::..................#"
    .ascii "#....F........$....::.............F....#"
    .ascii "#...................:..................#"
    .ascii "#.........:::::::::::::::::::::........#"
    .ascii "#.........:::::::::::::::::::::........#"
    .ascii "#.......*..........::..................#"
    .ascii "#............F.....::.....F............#"
    .ascii "#.,,,,,,,,.........::.........,,,,,,,,.#"
    .ascii "#.,,,,,,,,.........::.........,,,,,,,,.#"
    .ascii "#.,,,,,,,,.........::.........,,,,,,,,.#"
    .ascii "#.,,,,,,,,.........::.........,,,,,,,,.#"
    .ascii "#.,,,,,,,,.........::.........,,,,,,,,.#"
    .ascii "#.,,,,,,,,....~~~~~~~~~~~~....,,,,,,,,.#"
    .ascii "#.............~~~~~~~~~~~~.............#"
    .ascii "#.............~~~~~~~~~~~~.............#"
    .ascii "########################################"
    .byte 0
.globl map0_npcs
map0_npcs:
    .byte 17,10,0,5
    .quad str_npc_map0_npcs_17_10
    .zero 4                      # entity entries are 16 bytes
    .byte 11,9,0,2
    .quad str_npc_map0_npcs_11_9
    .zero 4                      # entity entries are 16 bytes
    .byte 24,16,0,1
    .quad str_npc_map0_npcs_24_16
    .zero 4                      # entity entries are 16 bytes
    .byte 0xff
    .zero 15
.globl map0_signs
map0_signs:
    .byte 21,2,0,0
    .quad str_sign_map0_signs_21_2
    .zero 4                      # entity entries are 16 bytes
    .byte 14,9,0,0
    .quad str_sign_map0_signs_14_9
    .zero 4                      # entity entries are 16 bytes
    .byte 0xff
    .zero 15
.globl map0_items
map0_items:
    .byte 8,13,0,0
    .quad str_item_map0_items_8_13
    .zero 4                      # entity entries are 16 bytes
    .byte 0xff
    .zero 15
.globl map0_links
map0_links:
    .byte 1,254,38
    .byte 0xff,0,0
    .byte 0xff,0,0
    .byte 0xff,0,0
.globl map0_warps
map0_warps:
    .byte 10,7,3,5,7
    .byte 30,7,3,6,7
    .byte 0xff
.globl map0_spawn
map0_spawn: .byte 19,10,40,24

.globl str_npc_map0_npcs_17_10
str_npc_map0_npcs_17_10: .asciz "PROF. OAK\fPOKeMON are my\ntrue love!\fWild ones live in\nthe tall grass.\fPress M for the\nmenu, Z to talk."
.globl str_npc_map0_npcs_11_9
str_npc_map0_npcs_11_9: .asciz "MOM\fAll boys leave\nhome some day.\fIt said so on TV!"
.globl str_npc_map0_npcs_24_16
str_npc_map0_npcs_24_16: .asciz "KID\fTall grass hides\nwild POKeMON.\fWalk in it and\nwatch out!"
.globl str_sign_map0_signs_21_2
str_sign_map0_signs_21_2: .asciz "PALLET TOWN\fShades of your\njourney await!"
.globl str_sign_map0_signs_14_9
str_sign_map0_signs_14_9: .asciz "RED's house\fMOM lives here."
.globl str_item_map0_items_8_13
str_item_map0_items_8_13: .asciz "\fYou found a\nPOTION!\fIt went into\nyour BAG."

# ----- map 1: ROUTE 1 (40x40) spawn (0, 0) -----
.globl map1_name
map1_name: .asciz "ROUTE 1"
.globl map1_tiles
map1_tiles:
    .ascii "##################....##################"
    .ascii "#..................::..................#"
    .ascii "#..................::..................#"
    .ascii "#....F.............::.............F....#"
    .ascii "#..................::.............*....#"
    .ascii "#..................::..................#"
    .ascii "#..,,,,,,,,........::........,,,,,,,,..#"
    .ascii "#..,,,,,,,,........::........,,,,,,,,..#"
    .ascii "#..,,,,,,,,........::........,,,,,,,,..#"
    .ascii "#..,,,,,,,,........::........,,,,,,,,..#"
    .ascii "#..,,,,,,,,........::........,,,,,,,,..#"
    .ascii "#..,,,,,,,,........::........,,,,,,,,..#"
    .ascii "#..,,,,,,,,........::........,,,,,,,,..#"
    .ascii "#..................::..................#"
    .ascii "#..................::..................#"
    .ascii "#............####..::...####...........#"
    .ascii "#............####..::...####...........#"
    .ascii "#............####..::...####...........#"
    .ascii "#..........F.####..::...####F..........#"
    .ascii "#..................::..................#"
    .ascii "#.......::::::::::::::::::::::::.......#"
    .ascii "#.......::::::::::::::::::::::::.......#"
    .ascii "#..................::..................#"
    .ascii "#..................::..................#"
    .ascii "#................F.::..................#"
    .ascii "#.....,,,,,,,,.....::.....,,,,,,,,.....#"
    .ascii "#.....,,,,,,,,.....::.....,,,,,,,,.....#"
    .ascii "#.....,,,,,,,,.....::.....,,,,,,,,.....#"
    .ascii "#.....,,,,,,,,.....::.....,,,,,,,,.....#"
    .ascii "#.....,,,,,,,,.....::.....,,,,,,,,.....#"
    .ascii "#.....,,,,,,,,.....::.....,,,,,,,,.....#"
    .ascii "#.....,,,,,,,,.....::.....,,,,,,,,.....#"
    .ascii "#..................::..................#"
    .ascii "#..................::.F................#"
    .ascii "#.~~~~~~~~~~~~~...$::..................#"
    .ascii "#.~~~~~~~~~~~~~....::..................#"
    .ascii "#.~~~~~~~~~~~~~....::..................#"
    .ascii "#.~~~~~~~~~~~~~....::..................#"
    .ascii "#..................::..................#"
    .ascii "##################....##################"
    .byte 0
.globl map1_npcs
map1_npcs:
    .byte 22,20,0,1
    .quad str_npc_map1_npcs_22_20
    .zero 4                      # entity entries are 16 bytes
    .byte 16,28,0,2
    .quad str_npc_map1_npcs_16_28
    .zero 4                      # entity entries are 16 bytes
    .byte 0xff
    .zero 15
.globl map1_signs
map1_signs:
    .byte 18,34,0,0
    .quad str_sign_map1_signs_18_34
    .zero 4                      # entity entries are 16 bytes
    .byte 0xff
    .zero 15
.globl map1_items
map1_items:
    .byte 34,4,1,0
    .quad str_item_map1_items_34_4
    .zero 4                      # entity entries are 16 bytes
    .byte 0xff
    .zero 15
.globl map1_links
map1_links:
    .byte 2,254,30
    .byte 0,254,2
    .byte 0xff,0,0
    .byte 0xff,0,0
.globl map1_warps
map1_warps:
    .byte 0xff
.globl map1_spawn
map1_spawn: .byte 0,0,40,40

.globl str_npc_map1_npcs_22_20
str_npc_map1_npcs_22_20: .asciz "YOUNGSTER JOEY\fI like shorts!\nThey're comfy\nand easy to wear!\f...My RATTATA is\nin the top\npercentage!"
.globl str_npc_map1_npcs_16_28
str_npc_map1_npcs_16_28: .asciz "BUG CATCHER\fTall grass rustles\nwhen you walk\nthrough it.\fSomething always\njumps out!"
.globl str_sign_map1_signs_18_34
str_sign_map1_signs_18_34: .asciz "ROUTE 1\fPALLET TOWN -\nVIRIDIAN CITY"
.globl str_item_map1_items_34_4
str_item_map1_items_34_4: .asciz "\fYou found a\nPOKe BALL!\fIt went into\nyour BAG."

# ----- map 2: VIRIDIAN CITY (48x32) spawn (0, 0) -----
.globl map2_name
map2_name: .asciz "VIRIDIAN CITY"
.globl map2_tiles
map2_tiles:
    .ascii "################################################"
    .ascii "#..................::..........................#"
    .ascii "#..................::..........................#"
    .ascii "#..................::.........~~~~~~~~~~~......#"
    .ascii "#..................::.........~~~~~~~~~~~......#"
    .ascii "#.......RRRRRRRR...::.........~~~~~~~~~~~R.....#"
    .ascii "#.......RRRRRRRR...::.........~~~~~~~~~~~R.....#"
    .ascii "#.......RRRRRRRR...::.............RRRRRRRR.....#"
    .ascii "#.......RRRRDRRR...::.............RRRRDRRR.....#"
    .ascii "#..................::.RRRRRRRR.................#"
    .ascii "#..................::.RRRRRRRR.................#"
    .ascii "#..................::.RRRRRRRR.................#"
    .ascii "#...F..............::.RRRRDRRR.F............F..#"
    .ascii "#..................::..........................#"
    .ascii "#.......*..........::..........................#"
    .ascii "#..................::..........................#"
    .ascii "#.....::::::::::::::::::::::::::::::::::::.....#"
    .ascii "#.....::::::::::::::::::::::::::::::::::::.....#"
    .ascii "#..................::..........................#"
    .ascii "#..................::..........................#"
    .ascii "#...F..............::.......................F..#"
    .ascii "#..................::.........RRRRRRRR.........#"
    .ascii "#..................::.........RRRRRRRR.........#"
    .ascii "#..................::.........RRRRRRRR.........#"
    .ascii "#..................::.........RRRRDRRR.........#"
    .ascii "#..................::..........................#"
    .ascii "#.,,,,,,,,,........::.................,,,,,,,,.#"
    .ascii "#.,,,,,,,,,........::.................,,,,,,,,.#"
    .ascii "#.,,,,,,,,,........::.$...............,,,,,,,,.#"
    .ascii "#.,,,,,,,,,........::.................,,,,,,,,.#"
    .ascii "#.,,,,,,,,,........::.................,,,,,,,,.#"
    .ascii "##################....##########################"
    .byte 0
.globl map2_npcs
map2_npcs:
    .byte 17,12,0,3
    .quad str_npc_map2_npcs_17_12
    .zero 4                      # entity entries are 16 bytes
    .byte 24,17,2,4
    .quad str_npc_map2_npcs_24_17
    .zero 4                      # entity entries are 16 bytes
    .byte 32,20,0,2
    .quad str_npc_map2_npcs_32_20
    .zero 4                      # entity entries are 16 bytes
    .byte 0xff
    .zero 15
.globl map2_signs
map2_signs:
    .byte 22,28,0,0
    .quad str_sign_map2_signs_22_28
    .zero 4                      # entity entries are 16 bytes
    .byte 0xff
    .zero 15
.globl map2_items
map2_items:
    .byte 8,14,0,0
    .quad str_item_map2_items_8_14
    .zero 4                      # entity entries are 16 bytes
    .byte 0xff
    .zero 15
.globl map2_links
map2_links:
    .byte 0xff,0,0
    .byte 1,254,1
    .byte 0xff,0,0
    .byte 0xff,0,0
.globl map2_warps
map2_warps:
    .byte 12,8,3,5,7
    .byte 38,8,3,6,7
    .byte 26,12,3,5,7
    .byte 34,24,3,6,7
    .byte 0xff
.globl map2_spawn
map2_spawn: .byte 0,0,48,32

.globl str_npc_map2_npcs_17_12
str_npc_map2_npcs_17_12: .asciz "CENTER GUIDE\fThe house with\nthe red roof is\nthe POKeMON\nCENTER.\fStep inside and\nthe nurse will\nheal your team."
.globl str_npc_map2_npcs_24_17
str_npc_map2_npcs_24_17: .asciz "RIVAL\fHey! You got a\nPOKeMON too?\fThen let's see\nhow good you\nreally are!"
.globl str_npc_map2_npcs_32_20
str_npc_map2_npcs_32_20: .asciz "GIRL\fThe road north is\nblocked by a\nsleepy man.\fYou could train\nin the grass to\nthe south!"
.globl str_sign_map2_signs_22_28
str_sign_map2_signs_22_28: .asciz "VIRIDIAN CITY\fThe ETERNAL\nCITY OF\nDREAMING."
.globl str_item_map2_items_8_14
str_item_map2_items_8_14: .asciz "\fYou found a\nPOTION!\fIt went into\nyour BAG."

# ----- map 3: POKeMON CENTER (12x9) spawn (5, 7) -----
.globl map3_name
map3_name: .asciz "POKeMON CENTER"
.globl map3_tiles
map3_tiles:
    .ascii "WWWWWWWWWWWW"
    .ascii "WLMMLLLLLLLW"
    .ascii "WCCCCLLLLLLW"
    .ascii "WLLLLLLLLLLW"
    .ascii "WLLLLLLLLLLW"
    .ascii "WLLLLLLLLLLW"
    .ascii "WLLLLLLLLLLW"
    .ascii "WLLLLLLLLLLW"
    .ascii "WWWWWDDWWWWW"
    .byte 0
.globl map3_npcs
map3_npcs:
    .byte 3,4,1,3
    .quad str_npc_map3_npcs_3_4
    .zero 4                      # entity entries are 16 bytes
    .byte 8,4,0,2
    .quad str_npc_map3_npcs_8_4
    .zero 4                      # entity entries are 16 bytes
    .byte 0xff
    .zero 15
.globl map3_signs
map3_signs:
    .byte 0xff
    .zero 15
.globl map3_items
map3_items:
    .byte 0xff
    .zero 15
.globl map3_links
map3_links:
    .byte 0xff,0,0
    .byte 0xff,0,0
    .byte 0xff,0,0
    .byte 0xff,0,0
.globl map3_warps
map3_warps:
    .byte 5,8,254,0,0
    .byte 6,8,254,0,0
    .byte 0xff
.globl map3_spawn
map3_spawn: .byte 5,7,12,9

.globl str_npc_map3_npcs_3_4
str_npc_map3_npcs_3_4: .asciz "NURSE\fWelcome to the\nPOKeMON CENTER!\fShall I heal\nyour POKeMON?"
.globl str_npc_map3_npcs_8_4
str_npc_map3_npcs_8_4: .asciz "MOM\fTake care out\nthere, RED!"

# -------------------------------------------------------- map table -----
.globl map_tilesets
.globl map_tilesets
map_tilesets:
    .byte 0,0,0,1

.globl map_table
.globl map_table
map_table:
    .quad map0_name, map0_tiles, map0_npcs, map0_signs
    .quad map0_items, map0_links, map0_warps, map0_spawn
    .quad map1_name, map1_tiles, map1_npcs, map1_signs
    .quad map1_items, map1_links, map1_warps, map1_spawn
    .quad map2_name, map2_tiles, map2_npcs, map2_signs
    .quad map2_items, map2_links, map2_warps, map2_spawn
    .quad map3_name, map3_tiles, map3_npcs, map3_signs
    .quad map3_items, map3_links, map3_warps, map3_spawn
.globl n_maps
.globl n_maps
n_maps: .byte 4

# ----------------------------------------------------------- strings -----
.globl str_title
str_title: .asciz "POKeMON"
.globl str_title2
str_title2: .asciz "FIRE RED"
.globl str_title3
str_title3: .asciz "ASM EDITION"
.globl str_start
str_start: .asciz "PRESS  START"
.globl str_credit
str_credit: .asciz "x86-64 asm . raw syscalls . no libc"
.globl str_intro1
str_intro1: .asciz "PROF. OAK\fHello there!\nWelcome to the\nworld of\nPOKeMON!"
.globl str_intro2
str_intro2: .asciz "PROF. OAK\fThis world is\ninhabited by\ncreatures\ncalled POKeMON!\fSome people\nraise them.\nSome battle\nwith them.\fMyself...\nI study them."
.globl str_intro3
str_intro3: .asciz "PROF. OAK\fChoose your\nfirst partner!"
.globl str_starter_a
str_starter_a: .asciz "This is\nCHARMANDER.\fA FIRE type.\nTake it?"
.globl str_starter_b
str_starter_b: .asciz "This is\nBULBASAUR.\fA GRASS type.\nTake it?"
.globl str_starter_c
str_starter_c: .asciz "This is\nSQUIRTLE.\fA WATER type.\nTake it?"
.globl str_yes
str_yes: .asciz "YES"
.globl str_no
str_no: .asciz "NO"
.globl str_nickname
str_nickname: .asciz "\fDo you want to\ngive it a\nnickname?\f...too bad, this\nis assembly.\nIt is "
.globl str_rival_pick
str_rival_pick: .asciz "\fRIVAL: Then\nI'll take this\none!"
.globl str_what_evo
str_what_evo: .asciz "What? "
.globl str_is_evolving
str_is_evolving: .asciz " is\nevolving!"
.globl str_congrats
str_congrats: .asciz "Congratulations!\nYour "
.globl str_evolved_into
str_evolved_into: .asciz "\nevolved into "
.globl str_wild
str_wild: .asciz "A wild "
.globl str_appeared
str_appeared: .asciz " appeared!"
.globl str_go
str_go: .asciz "I choose you!"
.globl str_what
str_what: .asciz "What will "
.globl str_do
str_do: .asciz " do?"
.globl str_run_ok
str_run_ok: .asciz "Got away\nsafely!"
.globl str_run_fail
str_run_fail: .asciz "Can't escape!"
.globl str_caught
str_caught: .asciz "Gotcha! "
.globl str_caught2
str_caught2: .asciz " was caught!"
.globl str_catchfail
str_catchfail: .asciz "Oh no! The\nPOKeMON broke\nfree!"
.globl str_fainted
str_fainted: .asciz " fainted!"
.globl str_gain_xp
str_gain_xp: .asciz " gained "
.globl str_xp_points
str_xp_points: .asciz " EXP. Points!"
.globl str_level_up
str_level_up: .asciz " grew to\nLv"
.globl str_win
str_win: .asciz "You won the\nbattle!"
.globl str_lv
str_lv: .asciz "Lv"
.globl str_hp
str_hp: .asciz "HP"
.globl str_notpp
str_notpp: .asciz "No PP left for\nthis move!"
.globl str_super
str_super: .asciz "It's super\neffective!"
.globl str_weak
str_weak: .asciz "It's not very\neffective..."
.globl str_noeff
str_noeff: .asciz "It doesn't\naffect..."
.globl str_atkdown
str_atkdown: .asciz "'s ATTACK\nfell!"
.globl str_defdown
str_defdown: .asciz "'s DEFENSE\nfell!"
.globl str_healmove
str_healmove: .asciz " recovered\nhealth!"
.globl str_poison
str_poison: .asciz " was poisoned!"
.globl str_poisondmg
str_poisondmg: .asciz " is hurt by\npoison!"
.globl str_recoil
str_recoil: .asciz " is hit by\nrecoil!"
.globl str_crit
str_crit: .asciz "A critical\nhit!"
.globl str_rivalbattle
str_rivalbattle: .asciz "RIVAL wants\nto fight!"
.globl str_whiteout
str_whiteout: .asciz "You have no\nPOKeMON left!\fYou whited out!\f...You scurried\nto the POKeMON\nCENTER."
.globl str_partyfull
str_partyfull: .asciz "Your party is\nfull!"
.globl str_sentout
str_sentout: .asciz " sent out "
.globl str_potion
str_potion: .asciz "POTION"
.globl str_poke_ball
str_poke_ball: .asciz "POKe BALL"
.globl str_usedpotion
str_usedpotion: .asciz " used a\nPOTION!"
.globl str_healed20
str_healed20: .asciz " recovered\n20 HP!"
.globl str_threwball
str_threwball: .asciz " threw a\nPOKe BALL!"
.globl str_bagempty
str_bagempty: .asciz "The BAG is\nempty."
.globl str_menu_hdr
str_menu_hdr: .asciz "MENU"
.globl str_pokedex
str_pokedex: .asciz "POKeDEX"
.globl str_pokemon_m
str_pokemon_m: .asciz "POKeMON"
.globl str_bag_m
str_bag_m: .asciz "BAG"
.globl str_player_m
str_player_m: .asciz "PLAYER"
.globl str_save_m
str_save_m: .asciz "SAVE"
.globl str_option_m
str_option_m: .asciz "OPTION"
.globl str_exit_m
str_exit_m: .asciz "EXIT"
.globl str_saved
str_saved: .asciz "Your progress\nhas been saved."
.globl str_savefail
str_savefail: .asciz "Saving failed\n(file I/O)."
.globl str_nosave
str_nosave: .asciz "No saved data\nfound."
.globl str_pkdx_none
str_pkdx_none: .asciz "No data yet.\fCatch POKeMON to\nfill the DEX!"
.globl str_noenc
str_noenc: .asciz "No encounters\nin ROUTE 1 yet."
.globl str_overwrite
str_overwrite: .asciz "Would you like\nto overwrite the\nprevious save?"
.globl str_playerinfo
str_playerinfo: .asciz "PLAYER: RED\fBADGES: 0\nMONEY: 3000\fPOKeDEX: "
.globl str_battle
str_battle: .asciz "BATTLE"
.globl str_fight
str_fight: .asciz "FIGHT"
.globl str_bagb
str_bagb: .asciz "BAG"
.globl str_pokemonb
str_pokemonb: .asciz "POKeMON"
.globl str_runb
str_runb: .asciz "RUN"
.globl str_ballused
str_ballused: .asciz " used a\nPOKe BALL!"
.globl str_dialog_ok
str_dialog_ok: .asciz "..."
.globl str_escaping
str_escaping: .asciz "..."

# battle menu labels
.globl battle_labels
battle_labels: .quad str_fight, str_bagb, str_pokemonb, str_runb
